### ISSUE TITLE
'type' field for component schema is not required

### ISSUE THREAD

**Issue by ffleader1** [basiliqio/oapi#3]
A component schema NewUser like this
```
    NewUser:
      # type: object
      required:
        - username
        - age
      properties:
        username:
          type: string
          description: Name of the pet
        age:
          type: integer
          description: user age
```
will break.
The reason is that it's missing ```type: object```. However, Oapi V3 Spec does not require ```type: object``` to be persented. The ```properties``` key make it implicit that the schema is object type.
